export const IMAGES_FETCH_SUCCESS = 'IMAGES_FETCH_SUCCESS';

export const FORM_FILE_CHANGED = 'FORM_FILE_CHANGED';

export const FORM_TEXT_CHANGED = 'FORM_TEXT_CHANGED';

export const FORM_TEXT_CLEAR = 'FORM_TEXT_CLEAR';

// CANVAS ACTIONS
export const CANVAS_ADD_IMAGE = 'CANVAS_ADD_IMAGE';

export const CANVAS_ADD_TEXT = 'CANVAS_ADD_TEXT';

export const CANVAS_TEXT_UPDATE_COORDS = 'CANVAS_TEXT_UPDATE_COORDS';

export const CANVAS_IMAGE_UPDATE_COORDS = 'CANVAS_IMAGE_UPDATE_COORDS';

export const CANVAS_IMAGE_REMOVE = 'CANVAS_IMAGE_REMOVE';

export const CANVAS_ITEM_REMOVE = 'CANVAS_ITEM_REMOVE';
