export const IMAGES_FETCH_SUCCESS = 'IMAGES_FETCH_SUCCESS';

export const FORM_FILE_CHANGED = 'FORM_FILE_CHANGED';

// CANVAS ACTIONS
export const CANVAS_ADD_IMAGE = 'CANVAS_ADD_IMAGE';

export const CANVAS_ADD_TEXT = 'CANVAS_ADD_TEXT';
